### ISSUE TITLE
404: NOT_FOUND

### ISSUE THREAD

**Issue by gorquan** [Hk-Gosuto/vercel-ai-proxy#1]
按照 README 描述的进行部署，部署后提示404: NOT_FOUND

**Comment by Hk-Gosuto** [comment]
只有下面的几个路由可以用，部署完只需要根据使用的服务填对应的转发地址就可以了

```
# openai
https://your_domian/openai/

# gemini
https://your_domian/gemini/

# groq
https://your_domian/groq/

# claude
https://your_domian/claude/

# cohere
https://your_domian/cohere/
```

**Comment by gorquan** [comment]
> 只有下面的几个路由可以用，部署完只需要根据使用的服务填对应的转发地址就可以了
> 
> ```
> # openai
> https://your_domian/openai/
> 
> # gemini
> https://your_domian/gemini/
> 
> # groq
> https://your_domian/groq/
> 
> # claude
> https://your_domian/claude/
> 
> # cohere
> https://your_domian/cohere/
> ```

是的 我用这些路径访问 也是提示404: NOT_FOUND

**Comment by gorquan** [comment]
我明白了，部署是没问题的
gemini 的话 https://your_domian/gemini
groq 的话 https://your_domian/groq/openai/v1
